// flow-typed signature: c3e7f5240a5995057ec7dbd0b164bdd1
// flow-typed version: <<STUB>>/del-webpack-plugin_v^1.0.6/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'del-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'del-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'del-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'del-webpack-plugin/example/App' {
  declare module.exports: any;
}

declare module 'del-webpack-plugin/example/App2' {
  declare module.exports: any;
}

declare module 'del-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'del-webpack-plugin/webpack.example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'del-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'del-webpack-plugin/dist/index'>;
}
declare module 'del-webpack-plugin/example/App.js' {
  declare module.exports: $Exports<'del-webpack-plugin/example/App'>;
}
declare module 'del-webpack-plugin/example/App2.js' {
  declare module.exports: $Exports<'del-webpack-plugin/example/App2'>;
}
declare module 'del-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'del-webpack-plugin/src/index'>;
}
declare module 'del-webpack-plugin/webpack.example.js' {
  declare module.exports: $Exports<'del-webpack-plugin/webpack.example'>;
}
