// flow-typed signature: f8002925a449da6123f7205d26e07d71
// flow-typed version: <<STUB>>/error-overlay-webpack-plugin_v^0.1.5/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'error-overlay-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'error-overlay-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'error-overlay-webpack-plugin/lib/entry' {
  declare module.exports: any;
}

declare module 'error-overlay-webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'error-overlay-webpack-plugin/lib/entry.js' {
  declare module.exports: $Exports<'error-overlay-webpack-plugin/lib/entry'>;
}
declare module 'error-overlay-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'error-overlay-webpack-plugin/lib/index'>;
}
