// flow-typed signature: f173497d1ff7d74c6aefe7addccda0c7
// flow-typed version: <<STUB>>/html-webpack-include-assets-plugin_v^1.0.4/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-include-assets-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-include-assets-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'html-webpack-include-assets-plugin/index' {
  declare module.exports: $Exports<'html-webpack-include-assets-plugin'>;
}
declare module 'html-webpack-include-assets-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-include-assets-plugin'>;
}
