// flow-typed signature: 72ecee3a8e53f88b50ecbf1455a687fe
// flow-typed version: <<STUB>>/postcss-preset-env_v^5.2.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-preset-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-preset-env/index.cjs' {
  declare module.exports: any;
}

declare module 'postcss-preset-env/index.es' {
  declare module.exports: any;
}

declare module 'postcss-preset-env/lib/get-transformed-insertions' {
  declare module.exports: any;
}

declare module 'postcss-preset-env/lib/get-unsupported-browsers-by-feature' {
  declare module.exports: any;
}

declare module 'postcss-preset-env/lib/ids-by-execution-order' {
  declare module.exports: any;
}

declare module 'postcss-preset-env/lib/plugins-by-id' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-preset-env/index.cjs.js' {
  declare module.exports: $Exports<'postcss-preset-env/index.cjs'>;
}
declare module 'postcss-preset-env/index.es.js' {
  declare module.exports: $Exports<'postcss-preset-env/index.es'>;
}
declare module 'postcss-preset-env/lib/get-transformed-insertions.js' {
  declare module.exports: $Exports<'postcss-preset-env/lib/get-transformed-insertions'>;
}
declare module 'postcss-preset-env/lib/get-unsupported-browsers-by-feature.js' {
  declare module.exports: $Exports<'postcss-preset-env/lib/get-unsupported-browsers-by-feature'>;
}
declare module 'postcss-preset-env/lib/ids-by-execution-order.js' {
  declare module.exports: $Exports<'postcss-preset-env/lib/ids-by-execution-order'>;
}
declare module 'postcss-preset-env/lib/plugins-by-id.js' {
  declare module.exports: $Exports<'postcss-preset-env/lib/plugins-by-id'>;
}
