// flow-typed signature: cef2f9ce6a3721a50ea9250871b45948
// flow-typed version: <<STUB>>/postcss-advanced-variables_v^2.3.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-advanced-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-advanced-variables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-advanced-variables/index.bundle' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/get-closest-variable' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/get-replaced-string' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/get-value-as-object' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/manage-unresolved' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/set-variable' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-content-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-decl' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-each-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-for-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-if-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-import-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-include-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-mixin-atrule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-node' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/transform-rule' {
  declare module.exports: any;
}

declare module 'postcss-advanced-variables/lib/waterfall' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-advanced-variables/index.bundle.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/index.bundle'>;
}
declare module 'postcss-advanced-variables/index' {
  declare module.exports: $Exports<'postcss-advanced-variables'>;
}
declare module 'postcss-advanced-variables/index.js' {
  declare module.exports: $Exports<'postcss-advanced-variables'>;
}
declare module 'postcss-advanced-variables/lib/get-closest-variable.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/get-closest-variable'>;
}
declare module 'postcss-advanced-variables/lib/get-replaced-string.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/get-replaced-string'>;
}
declare module 'postcss-advanced-variables/lib/get-value-as-object.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/get-value-as-object'>;
}
declare module 'postcss-advanced-variables/lib/manage-unresolved.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/manage-unresolved'>;
}
declare module 'postcss-advanced-variables/lib/set-variable.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/set-variable'>;
}
declare module 'postcss-advanced-variables/lib/transform-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-content-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-content-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-decl.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-decl'>;
}
declare module 'postcss-advanced-variables/lib/transform-each-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-each-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-for-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-for-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-if-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-if-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-import-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-import-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-include-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-include-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-mixin-atrule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-mixin-atrule'>;
}
declare module 'postcss-advanced-variables/lib/transform-node.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-node'>;
}
declare module 'postcss-advanced-variables/lib/transform-rule.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/transform-rule'>;
}
declare module 'postcss-advanced-variables/lib/waterfall.js' {
  declare module.exports: $Exports<'postcss-advanced-variables/lib/waterfall'>;
}
