// flow-typed signature: f6afff75b21feb694e66b5d49c8cc6d5
// flow-typed version: <<STUB>>/postcss-normalize_v^6.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-normalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-normalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-normalize/index.cjs' {
  declare module.exports: any;
}

declare module 'postcss-normalize/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-normalize/index.cjs.js' {
  declare module.exports: $Exports<'postcss-normalize/index.cjs'>;
}
declare module 'postcss-normalize/index.es.js' {
  declare module.exports: $Exports<'postcss-normalize/index.es'>;
}
