// flow-typed signature: ae35e9a640fbcd7181f60d89da54184b
// flow-typed version: <<STUB>>/postcss-jsx_v^0.32.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-jsx/camel-case' {
  declare module.exports: any;
}

declare module 'postcss-jsx/extract' {
  declare module.exports: any;
}

declare module 'postcss-jsx/get-template' {
  declare module.exports: any;
}

declare module 'postcss-jsx/literal' {
  declare module.exports: any;
}

declare module 'postcss-jsx/object-parse' {
  declare module.exports: any;
}

declare module 'postcss-jsx/object-parser' {
  declare module.exports: any;
}

declare module 'postcss-jsx/object-stringifier' {
  declare module.exports: any;
}

declare module 'postcss-jsx/object-stringify' {
  declare module.exports: any;
}

declare module 'postcss-jsx/object-syntax' {
  declare module.exports: any;
}

declare module 'postcss-jsx/object' {
  declare module.exports: any;
}

declare module 'postcss-jsx/un-camel-case' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-jsx/camel-case.js' {
  declare module.exports: $Exports<'postcss-jsx/camel-case'>;
}
declare module 'postcss-jsx/extract.js' {
  declare module.exports: $Exports<'postcss-jsx/extract'>;
}
declare module 'postcss-jsx/get-template.js' {
  declare module.exports: $Exports<'postcss-jsx/get-template'>;
}
declare module 'postcss-jsx/index' {
  declare module.exports: $Exports<'postcss-jsx'>;
}
declare module 'postcss-jsx/index.js' {
  declare module.exports: $Exports<'postcss-jsx'>;
}
declare module 'postcss-jsx/literal.js' {
  declare module.exports: $Exports<'postcss-jsx/literal'>;
}
declare module 'postcss-jsx/object-parse.js' {
  declare module.exports: $Exports<'postcss-jsx/object-parse'>;
}
declare module 'postcss-jsx/object-parser.js' {
  declare module.exports: $Exports<'postcss-jsx/object-parser'>;
}
declare module 'postcss-jsx/object-stringifier.js' {
  declare module.exports: $Exports<'postcss-jsx/object-stringifier'>;
}
declare module 'postcss-jsx/object-stringify.js' {
  declare module.exports: $Exports<'postcss-jsx/object-stringify'>;
}
declare module 'postcss-jsx/object-syntax.js' {
  declare module.exports: $Exports<'postcss-jsx/object-syntax'>;
}
declare module 'postcss-jsx/object.js' {
  declare module.exports: $Exports<'postcss-jsx/object'>;
}
declare module 'postcss-jsx/un-camel-case.js' {
  declare module.exports: $Exports<'postcss-jsx/un-camel-case'>;
}
