// flow-typed signature: 7b8eae2251237e4e7b827d8a2848e08e
// flow-typed version: <<STUB>>/stylelint-no-unsupported-browser-features_v^3.0.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-no-unsupported-browser-features'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-no-unsupported-browser-features' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-no-unsupported-browser-features/lib/index' {
  declare module.exports: any;
}

declare module 'stylelint-no-unsupported-browser-features/lib/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-no-unsupported-browser-features/lib/index.js' {
  declare module.exports: $Exports<'stylelint-no-unsupported-browser-features/lib/index'>;
}
declare module 'stylelint-no-unsupported-browser-features/lib/index.test.js' {
  declare module.exports: $Exports<'stylelint-no-unsupported-browser-features/lib/index.test'>;
}
